spring:
  servlet:
    multipart:
      # 限制文件上传大小
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # springboot2.6以上版本和swagger3.0冲突的问题

server:
  servlet:
    encoding:
      force: true # 解决静态资源乱码问题